/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./malware/asp/APT_APT1_asp.yar"
include "./malware/asp/TOOLKIT_THOR_HackTools_asp.yar"
include "./webshells/asp/WShell_APT_Laudanum_asp.yar"
include "./webshells/asp/WShell_THOR_Webshells_asp.yar"
