/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./malware/aspx/APT_Irontiger_aspx.yar"
include "./webshells/aspx/WShell_APT_Laudanum_aspx.yar"
include "./webshells/aspx/WShell_ASPXSpy_aspx.yar"
include "./webshells/aspx/WShell_THOR_Webshells_aspx.yar"
