/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./malware/bat/APT_EQUATIONGRP_bat.yar"
include "./malware/bat/APT_Sofacy_Bundestag_bat.yar"
include "./malware/bat/TOOLKIT_THOR_HackTools_bat.yar"
