/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./cve_rules/Linux/CVE-2016-5195.yar"
include "./cve_rules/ace/CVE-2018-20250_ace.yar"
include "./cve_rules/jar/CVE-2010-0887_jar.yar"
include "./cve_rules/jar/CVE-2013-0422_jar.yar"
include "./cve_rules/office/CVE-2012-0158.yar"
include "./cve_rules/office/CVE-2017-11882.yar"
include "./cve_rules/pe/CVE-2010-0805_pe.yar"
include "./cve_rules/pe/CVE-2015-1701_pe.yar"
include "./cve_rules/pe/CVE-2015-2426_pe.yar"
include "./cve_rules/pe/CVE-2015-2545_pe.yar"
include "./cve_rules/swf/CVE-2010-1297_swf.yar"
include "./cve_rules/swf/CVE-2015-5119_swf.yar"
include "./cve_rules/swf/CVE-2018-4878_swf.yar"
include "./cve_rules/xap/CVE-2013-0074_xap.yar"
