/*
Generated by YARA_Rules_Util
On 2021-08-28
*/
include "./email/attachment.yar"
include "./email/EMAIL_Cryptowall.yar"
include "./email/Email_fake_it_maintenance_bulletin.yar"
include "./email/Email_generic_phishing.yar"
include "./email/Email_quota_limit_warning.yar"
include "./email/email_Ukraine_BE_powerattack.yar"
include "./email/extortion_email.yar"
include "./email/image.yar"
include "./email/scam.yar"
include "./email/urls.yar"
include "./email/osx/Email_PHP_Mailer_osx.yar"
include "./email/zip/email_cryptowall_zip.yar"
