/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./malware/evt/MALW_Andromeda_evt.yar"
include "./malware/evt/MALW_Kovter_evt.yar"
include "./malware/evt/MALW_Lateral_Movement_evt.yar"
include "./malware/evt/POS_BruteforcingBot_evt.yar"
include "./malware/evt/RAT_DarkComet_evt.yar"
include "./malware/evt/RAT_Xtreme_evt.yar"
