/*
Generated by YARA_Rules_Util
On 2021-08-28
*/
include "./cve_rules/jar/CVE-2010-0887_jar.yar"
include "./cve_rules/jar/CVE-2013-0422_jar.yar"
include "./exploit_kits/jar/EK_Angler_jar.yar"
include "./exploit_kits/jar/EK_Blackhole_jar.yar"
include "./exploit_kits/jar/EK_BleedingLife_jar.yar"
include "./exploit_kits/jar/EK_Crimepack_jar.yar"
include "./exploit_kits/jar/EK_Eleonore_jar.yar"
include "./exploit_kits/jar/EK_Phoenix_jar.yar"
include "./exploit_kits/jar/EK_Sakura_jar.yar"
include "./malware/jar/APT_eqgrp_apr17_jar.yar"
include "./malware/jar/MALW_adwind_RAT_jar.yar"
include "./malware/jar/MALW_MacGyver_jar.yar"
include "./malware/jar/RAT_Adwind_jar.yar"
include "./malware/jar/RAT_Adzok_jar.yar"
include "./malware/jar/RAT_Crimson_jar.yar"
include "./malware/jar/RAT_CrossRAT_jar.yar"
include "./malware/jar/RAT_Ratdecoders_jar.yar"
