/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./malware/js/APT_TradeSecret_js.yar"
include "./packers/js/Javascript_exploit_and_obfuscation_js.yar"
include "./packers/js/JJencode_js.yar"
include "./webshells/js/WShell_THOR_Webshells_js.yar"
