/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./malware/jsp/APT_Irontiger_jsp.yar"
include "./malware/jsp/TOOLKIT_THOR_HackTools_jsp.yar"
include "./webshells/jsp/WShell_APT_Laudanum_jsp.yar"
include "./webshells/jsp/WShell_THOR_Webshells_jsp.yar"
