/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./packers/js/Javascript_exploit_and_obfuscation_js.yar"
include "./packers/js/JJencode_js.yar"
include "./packers/pe/packer_compiler_signatures_pe.yar"
include "./packers/pe/packer_pe.yar"
include "./packers/pe/peid_pe.yar"
