/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./packers/elf/Golang_elf.yar"
include "./packers/js/Javascript_exploit_and_obfuscation_js.yar"
include "./packers/js/JJencode_js.yar"
include "./packers/pe/Golang_pe.yar"
include "./packers/pe/packer_compiler_signatures_pe.yar"
include "./packers/pe/packer_pe.yar"
include "./packers/pe/peid_pe.yar"
include "./packers/zip/tweetable-polyglot-png_zip.yar"
