/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./exploit_kits/pdf/EK_Blackhole_pdf.yar"
include "./exploit_kits/pdf/EK_Phoenix_pdf.yar"
include "./maldocs/pdf/Maldoc_PDF_pdf.yar"
include "./malware/pdf/APT_NGO_pdf.yar"
include "./malware/pdf/APT_Waterbug_pdf.yar"
