/*
Generated by YARA_Rules_Util
On 2021-03-09
*/
include "./malware/php/APT_APT29_Grizzly_Steppe_php.yar"
include "./malware/php/MALW_Magento_backend_php.yar"
include "./malware/php/MALW_Magento_frontend_php.yar"
include "./malware/php/MALW_Magento_suspicious_php.yar"
include "./malware/php/RAT_Havex_php.yar"
include "./webshells/php/WShell_APT_Laudanum_php.yar"
include "./webshells/php/WShell_ChinaChopper_php.yar"
include "./webshells/php/Wshell_ChineseSpam_php.yar"
include "./webshells/php/wshell_drupalgeddon2_icos_php.yar"
include "./webshells/php/Wshell_fire2013_php.yar"
include "./webshells/php/WShell_PHP_Anuna_php.yar"
include "./webshells/php/WShell_THOR_Webshells_php.yar"
