/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./malware/pl/APT_eqgrp_apr17_pl.yar"
include "./malware/pl/APT_EQUATIONGRP_pl.yar"
include "./malware/pl/TOOLKIT_THOR_HackTools_pl.yar"
include "./webshells/pl/WShell_THOR_Webshells_pl.yar"
