/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./malware/ps1/APT_Cobalt_ps1.yar"
include "./malware/ps1/APT_Oilrig_ps1.yar"
include "./malware/ps1/GEN_PowerShell_ps1.yar"
include "./malware/ps1/MALW_Empire_ps1.yar"
include "./malware/ps1/MALW_Miscelanea_ps1.yar"
include "./malware/ps1/TOOLKIT_THOR_HackTools_ps1.yar"
