/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./capabilities/ps1/Capabilities_ps1.yar"
include "./capabilities/ps1/Risky_Operations_ps1.yar"
include "./malware/ps1/APT_Cobalt_ps1.yar"
include "./malware/ps1/APT_Oilrig_ps1.yar"
include "./malware/ps1/GEN_PowerShell_ps1.yar"
include "./malware/ps1/MALW_Empire_ps1.yar"
include "./malware/ps1/MALW_Miscelanea_ps1.yar"
include "./malware/ps1/TOOLKIT_THOR_HackTools_ps1.yar"
