/*
Generated by YARA_Rules_Util
On 2021-03-09
*/
include "./malware/py/APT_eqgrp_apr17_py.yar"
include "./malware/py/APT_EQUATIONGRP_py.yar"
include "./malware/py/APT_Stuxnet_py.yar"
include "./malware/py/MALW_BackdoorSSH_py.yar"
include "./malware/py/MALW_PyPI_py.yar"
include "./malware/py/RAT_PoetRATPython_py.yar"
include "./webshells/py/WShell_THOR_Webshells_py.yar"
