/*
Generated by YARA_Rules_Util
On 2020-10-23
*/
include "./maldocs/rtf/Maldoc_APT19_CVE-2017-0199_rtf.yar"
include "./maldocs/rtf/Maldoc_CVE-2017-0199_rtf.yar"
include "./maldocs/rtf/Maldoc_CVE_2017_8759_rtf.yar"
include "./maldocs/rtf/Maldoc_malrtf_ole2link_rtf.yar"
include "./maldocs/rtf/maldoc_somerules_rtf.yar"
include "./malware/rtf/APT_Mongall_rtf.yar"
include "./malware/rtf/APT_Poseidon_Group_rtf.yar"
