/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./cve_rules/swf/CVE-2010-1297_swf.yar"
include "./cve_rules/swf/CVE-2015-5119_swf.yar"
include "./cve_rules/swf/CVE-2018-4878_swf.yar"
include "./exploit_kits/swf/EK_Angler_swf.yar"
include "./exploit_kits/swf/EK_BleedingLife_swf.yar"
