/*
Generated by YARA_Rules_Util
On 2021-08-28
*/
include "./utils/base64.yar"
include "./utils/domain.yar"
include "./utils/ip.yar"
include "./utils/magic.yar"
include "./utils/suspicious_strings.yar"
include "./utils/url.yar"
include "./utils/virustotal.yar"
