/*
Generated by YARA_Rules_Util
On 2022-06-17
*/
include "./malware/vbs/APT_Blackenergy_vbs.yar"
include "./malware/vbs/APT_Minidionis_vbs.yar"
include "./malware/vbs/APT_Oilrig_vbs.yar"
include "./malware/vbs/MALW_BlackWorm_vbs.yar"
include "./malware/vbs/MALW_FUDCrypt_vbs.yar"
include "./malware/vbs/TOOLKIT_THOR_HackTools_vbs.yar"
